### ISSUE TITLE
Does not output a TOC

### ISSUE THREAD

**Issue by GSNord** [PhilippMundhenk/Kirby-Table-of-Contents#2]
I would like to use this for my FAQ section.

I marked my headlines like
(l2: Question 1)
...
(l2: Question 2)
etc.

and placed the (toc: 6) tag at the top of my page.
### What it does

It creates the anchors for all of my headlines. However, I get the following errors

Notice: Undefined variable: cnt in D:\Test\CMS\kirby-bootstrap-starterkit\site\tags\sections.php on line 9
Notice: Undefined variable: splitchar in D:\Test\CMS\kirby-bootstrap-starterkit\site\tags\sections.php on line 39
Notice: Undefined variable: lowercase in D:\Test\CMS\kirby-bootstrap-starterkit\site\tags\sections.php on line 40

for each l1 heading, as l1 is handled aroud these lines. The same errors occur for l2, l3 etc. on the respective lines.
### What it does not

I does not output any TOC. Seems the (toc: 6) tag is ignored or does not produce any output.

**Comment by PhilippMundhenk** [comment]
Unfortunately, I cannot reproduce your error. Do you use the newest version?

I just set up a plain new Kirby with nothing in it, except this plugin, downloaded directly from GitHub. It works as it should with this example page content:

(toc: 6)
tag at the top of my page.

I marked my headlines like
(l2: Question 1)
Answer1

(l2: Question 2)
Answer2

(l3: Question 3)
Answer3

(l4: Question 4)
Answer4

(l5: Question 5)
Answer5

(l6: Question 6)
Answer6

You can see the result here: http://www.mundhenk.org/kirbyPlain/testtoc

**Comment by GSNord** [comment]
Hi Philipp,

I installed Kirby 2.2.3 as of 13th May, including the Panel. Seems there came Kirby 2.3.0 three days later, which I did not notice yet.
Further, I use the "Kirby CMS Bootstrap Blog Starterkit" from getkirby-themes.com as a base for my own development. However this package does not include any Kirby core version, just the content files.
Should I update to Kirby 2.3.0?

I checked again; it makes no difference if I use just (toc: 6) or use (toc:6 split: - lowercase: 1 levelchar: >)
I think the split, lowercase and levelchar parameters are optional?
These are my PHP messages: (I have a php_development.ini on my local system)

_Notice: Undefined variable: cnt in D:\Test\CMS\kirby-bootstrap-starterkit\site\tags\sections.php on line 9
Notice: Undefined variable: splitchar in D:\Test\CMS\kirby-bootstrap-starterkit\site\tags\sections.php on line 39
Notice: Undefined variable: lowercase in D:\Test\CMS\kirby-bootstrap-starterkit\site\tags\sections.php on line 40_
resulting from the different (l1:) etc. tags. Seems there are some variable uninitialized.

Looking at the sections.php code, when I replace line 285
`$html = "";`
by
`$html = "TOC goes here";`

I get this message output, so the (toc) tag code gets executed, but does not produce any additional output.

**Comment by GSNord** [comment]
Have been diving into your code...

Line 295
`preg_match_all("/\(l[1-6]?: .*\)/", $link, $headings);`

_$link_ is the complete path and filename of my contentfile in my case.
_$headings_ is the array where _preg_match_all_ should place its results.

I dumped _$headings_ and it is empty in my case.
Can _preg_match_all_ operate on files? Do I miss some PHP option setting or some global option for the preg function family?

Regards,
Bernward

**Comment by PhilippMundhenk** [comment]
The Kirby version should definitely not be an issue. I developed this quite some time ago, with older versions of Kirby. 
The parameters for toc are indeed optional. 
I need to clean up the code a bit to remove the notices you are getting. But this should also have nothing to do with your missing output.

Regarding the $headings being empty: This is indeed strange. In fact, $link should contain the complete content of your page, not the path and file name. Otherwise preg_match_all will not work. Could you dump $tag->page()->content() for me, please?

**Comment by GSNord** [comment]
I have rewritten and simplified the code already. Now everything works perfect for me.
Main changes:
- inserted a function to determine the splitchar and lowercase parameter in each of the (lx:) tag functions
- I scan the $page->text() filed instead of the complete content file or even a file reference
- I do not support parameters to the (lx: ) tags any more; I use only the (toc: ) parameters, because splitchar and lowercase must be the same for (lx: ) and (toc: ). Otherwise the links will not work.

I attached my version of the code. Because .php files are not supported here, I renamed it to .txt

PS: I had some PHP and/or browser crashes when using the vardump function, so I am now careful with that.

[sections_v2.txt](https://github.com/PhilippMundhenk/Kirby-Table-of-Contents/files/329556/sections_v2.txt)

**Comment by PhilippMundhenk** [comment]
Hi,
at first, I have to admit that this issue completely dropped out of my sight. I rediscovered it just now only. I remember you fixed things for you so I guess somehow that made me forget about it. 
I tested your solution and it works great! Thank you very much for the fixes. Would you like to create a pull request so that I can add your code with proper attribution or shall I simply merge it in?

**Comment by GSNord** [comment]
Hi Philipp,

I am absolutely not familiar with the dev processes on github. Pull 
request, that sounds complicated. I'm technician, not software developer.

So just take my code and merge it in (that sounds easy to me ;-)

Regards,
Bernward

**Comment by PhilippMundhenk** [comment]
Alright, done. Thank you very much for your support!
